# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Test env variables
      env:
        INTEGRATION_BOT_TOKEN: 'Test1'
        DEV_SERVER_TOKEN: 'Test2'
        DEV_STAFF_ROLES: 'Test3'
        DEV_RP_COMMANDS_CHANNEL: 'Test4'
        RP_APP_CHANNEL: 'Test5'
        DEV_ERROR_CHANNEL: 'Test6'
        DEV_CB_APP_CHANNEL: ${{ secrets.DEV_CB_APP_CHANNEL }}
      run: echo -Dspring-boot.run.arguments="ardaslegends.bot.token=$INTEGRATION_BOT_TOKEN,ardaslegends.bot.server=$DEV_SERVER_TOKEN,ardaslegends.bot.staff-roles=$DEV_STAFF_ROLES,ardaslegends.roleplay.commands.channel=$DEV_RP_COMMANDS_CHANNEL,ardaslegends.roleplay.apps.channel=$DEV_RP_APPS_CHANNEL,ardaslegends.bot.error.channel=$DEV_ERROR_CHANNEL"
        
    - name: Build with Maven
      env:
        INTEGRATION_BOT_TOKEN: ${{ secrets.INTEGRATION_BOT_TOKEN }}
        DEV_SERVER_TOKEN: ${{ secrets.DEV_SERVER_TOKEN }}
        DEV_STAFF_ROLES: ${{ secrets.DEV_STAFF_ROLES }}
        DEV_RP_COMMANDS_CHANNEL: ${{ secrets.DEV_RP_COMMANDS_CHANNEL }}
        DEV_RP_APPS_CHANNEL: ${{ secrets.DEV_RP_APPS_CHANNEL }}
        DEV_ERROR_CHANNEL: ${{ secrets.DEV_ERROR_CHANNEL }}
        DEV_CB_APP_CHANNEL: ${{ secrets.DEV_CB_APP_CHANNEL }}
      run: mvn -B clean verify --file pom.xml -D"ardaslegends.bot.token"=$INTEGRATION_BOT_TOKEN -D"ardaslegends.bot.server"=$DEV_SERVER_TOKEN -D"ardaslegends.bot.staff-roles"=$DEV_STAFF_ROLES -D"ardaslegends.roleplay.commands.channel"=$DEV_RP_COMMANDS_CHANNEL -D"ardaslegends.roleplay.apps.channel"=$DEV_RP_APPS_CHANNEL -D"ardaslegends.bot.error.channel"=$DEV_ERROR_CHANNEL -D"ardaslegends.claimbuild.apps.channel"=$DEV_CB_APP_CHANNEL -D"spring.sql.init.mode"=always -D"spring.jpa.defer-datasource-initialization"=true -D"spring.flyway.enabled"=false
